#!/bin/bash

fileName="${1%%.*}" # base filename

if [ -f "${fileName}.s" ]; then
    fileSrc="${fileName}.s"
elif [ -f "${fileName}.asm" ]; then
    fileSrc="${fileName}.asm"
else
    echo "unsupported extension"
    exit 1
fi

nasm -f elf64 "${fileSrc}"
ld "${fileName}.o" -o "${fileName}"
[ "$2" == "-g" ] && gdb -q ${fileName} || ./${fileName}
