#!/bin/sh
#BASE_DIR="$HOME/data/media/images/flameshot"
BASE_DIR="/mnt/data/media/images/flameshot"
SAVE_DIR="$BASE_DIR/$(date +'%Y-%m')"
mkdir -p "$SAVE_DIR"
flameshot gui -p "$SAVE_DIR" -c # ensure savePath does not exist in flameshot.ini

sleep 1

# find & delete files in ~/Pictures created in last 6s
# this is due to flameshot gui creating duplicate from savePath
find ~/Pictures -maxdepth 1 -type f -cmin -0.1 -name "Screenshot_*.png" -delete
